language: node_js
node_js:
  - 8.0

sudo: false

os:
  - linux
  - osx

install:
  - npm install eslint

script:
  - ./node_modules/eslint/bin/eslint.js ./lib

env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable

branches:
  only:
    - master

